name: Update README with OpenAI

on:
  push:
    branches: [ "main" ] # Cambia esto si usas otra rama principal
  workflow_dispatch: # Permite ejecuci칩n manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Timeout para evitar ejecuciones largas
    
    permissions:
      contents: write # Permisos para escribir archivos
      
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests
          
      - name: Generate/Update README and individual docs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/scripts/update_readme.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name "游뱄 Documentation Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git add "*.md"
          git diff --quiet && git diff --staged --quiet || git commit -m "游닄 Actualizar documentaci칩n autom치ticamente
          
          - README.md actualizado
          - Documentaci칩n individual para archivos .esql generada
          - Generado autom치ticamente por GitHub Actions + OpenAI"
          git push